### ISSUE TITLE
Bug: Docker部署启动后报错 exec format error

### ISSUE THREAD

**Issue by koking0** [nonebot/nonebot2#1424]
**描述问题：**

按照部署文档[使用 Docker 部署](https://v2.nonebot.dev/docs/tutorial/deployment#%E4%BD%BF%E7%94%A8-docker-%E9%83%A8%E7%BD%B2%E6%8E%A8%E8%8D%90)，配合 GitHub Actions 做 CI/CD，最后启动的时候报错：exec /start.sh: exec format error。

**如何复现？**

按照文档[使用 Docker 部署](https://v2.nonebot.dev/docs/tutorial/deployment#%E4%BD%BF%E7%94%A8-docker-%E9%83%A8%E7%BD%B2%E6%8E%A8%E8%8D%90)执行。

Dockerfile文件：
```
FROM python:3.9 as requirements-stage

WORKDIR /tmp

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN curl -sSL https://install.python-poetry.org -o install-poetry.py

RUN python install-poetry.py --yes

ENV PATH="${PATH}:/root/.local/bin"

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app

COPY --from=requirements-stage /tmp/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN rm requirements.txt

COPY ./ /app/
```

docker-compose.yml文件：
```
version: "3"
services:
  qq_bot_2:
    image: liuzhaofeng/matrix-bot:master
    ports:
      - "8002:8002"
    env_file:
      - ".env"
    environment:
      - ENVIRONMENT=dev # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
      - APP_MODULE=bot_beta:app # 配置 asgi 入口
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接
    network_mode: bridge
```

**期望的结果**

容器能够正常启动。
猜测报错原因是硬件架构不兼容，可否提供符合下述系统镜像的Dockerfile。

**环境信息：**

 - OS: Ubuntu 18.04.3 LTS aarch64
 - Python Version: 3.9.13
 - Nonebot Version: nonebot2==v2.0.0-beta.5

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: [v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3)

**截图或日志**

GitHub Actions执行成功：
![image](https://user-images.githubusercontent.com/45281765/204118618-9cb895df-9886-4d3a-ae1b-042c252077f7.png)

通过docker-compose前台启动：
![image](https://user-images.githubusercontent.com/45281765/204118667-c3ca44d9-8539-40a1-b4b5-5cee03ebccdd.png)

自己尝试解决的时候，试了官网的tiangolo/uvicorn-gunicorn-fastapi:python3.9和flyingjoe/uvicorn-gunicorn-fastapi:python3.9，但最后的报错是一样的。
