### ISSUE TITLE
can't use nonebot_plugin_apscheduler

### ISSUE THREAD

**Issue by huang12zheng** [nonebot/nonebot2#151]
**描述问题：**
can't use nonebot_plugin_apscheduler

* pyproject.toml
```toml

[tool.poetry.dependencies]
python = "^3.7"
nonebot2 = "^2.0.0a8"
nb-cli = "^0.1.0"
redis = "^3.5.3"
apscheduler = "^3.6.3"
nonebot_plugin_apscheduler = "^0.1.0"
```
* bot.py
```py

nonebot.init(
    apscheduler_config={
        "apscheduler.timezone": "Asia/Shanghai"
    }
)
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)
nonebot.load_builtin_plugins()
nonebot.load_plugins("src/plugins")
nonebot.load_plugin("nonebot_plugin_apscheduler")

```
* somepy.py
```py
from nonebot import on_command,require

ascheduler = require('nonebot_plugin_apscheduler').scheduler()  # ERROR

```

**如何复现？**

nb run (debug)

**期望的结果**

required success

**环境信息：**

 - OS: [e.g. Linux] 
   Linux 7181010ab2e6 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
 - Python Version: [e.g. 3.8]
 - Nonebot Version: [e.g. 2.0.0a8]

**截图**
![截屏2021-01-13 上午1 13 55 (2)](https://user-images.githubusercontent.com/28038074/104348776-18100080-553d-11eb-864c-cb779093dd50.png)
![截屏2021-01-13 上午1 23 53 (2)](https://user-images.githubusercontent.com/28038074/104349548-0713bf00-553e-11eb-814b-a773ae00771a.png)
