### ISSUE TITLE
get_bots无法获取bot

### ISSUE THREAD

**Issue by fake2ky** [nonebot/nonebot2#866]
**描述问题：**

  我在bot开放了一个msg的http接口, 在云端通过http://127.0.0.1:9326/msg?msg=xxxx来发送消息, 但是在发送消息经常会出现无法获取bot的情况(get_bots). 
  我尝试在代码了增加重试来等待机器人重新连接, cq部署在本地
  但是nonbot还是经常出现这种情况.

**如何复现？**

```
@app.get("/msg/")
async def hello():
    bots = nonebot.get_bots()
    while not bots:
        nonebot.log.logger.warning("等待中, 没有可用机器人...")
        await asyncio.sleep(1)
        bots = nonebot.get_bots()
    for bot in bots:
        b: Bot = bots.get(bot)
        await b.call_api('send_group_msg', **{
            'group_id': 群号,
            'message': 'test'
        })
```

**期望的结果**
  正常发送消息

**环境信息：**

 - OS: 腾讯云centos7
 - Python Version: 3.8
 - Nonebot Version: v2.0.0-beta.1

**协议端信息：**

 - 协议端: go-cqhttp
 - 协议端版本: v1.0.0-rc1 

**截图或日志**
![image](https://user-images.githubusercontent.com/31437813/158002098-61bc9dd3-6f61-4300-8a51-f7422bb95a2f.png)
===================== 尝试在本地断开CQ再重新连接CQ =========================
![image](https://user-images.githubusercontent.com/31437813/158002136-5ada0129-12aa-4323-8857-75fa6f03de68.png)

**Comment by mnixry** [comment]
很怪的问题, 观察到您似乎是在docker里面运行的, 可以发一下dockerfile或者类似的东西让我们参考一下吗

**Comment by yanyongyu** [comment]
机器人能否正常接收事件？

**Comment by yanyongyu** [comment]
也有可能是你启动了多个worker导致的，bot连接的worker和你api请求的worker不一致就获取不到bot了。

一般建议只开一个worker（或者自己做跨进程共享

**Comment by fake2ky** [comment]
> 很怪的问题, 观察到您似乎是在docker里面运行的, 可以发一下dockerfile或者类似的东西让我们参考一下吗
dockerfile

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
#
RUN python3 -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

RUN python3 -m pip install poetry && poetry config virtualenvs.create false

COPY pyproject.toml ./poetry.lock* .env* /app/

COPY ./lib /app/lib/

RUN ln -sf /app/lib/libtaos.so

RUN poetry install --no-root --no-dev
```
docker-compose
```
version: "2"
services:
  nonebot:
    container_name: nonebot
    build: .
    volumes:
      - "./:/app/"
      - "/usr/local/taos/driver/libtaos.so.2.4.0.5:/usr/lib/libtaos.so"
      - "/etc/taos/taos.cfg:/etc/taos/taos.cfg"
    extra_hosts:
      - "VM-12-14-centos:172.17.0.1"
    ports:
      - "9326:9326"
    env_file:
      - ".env.prod"
    environment:
      - TZ=Asia/Shanghai
      - ENVIRONMENT=prod
      - APP_MODULE=bot:app
      - SECRET=
      - ACCESS_TOKEN=
    network_mode: bridge
```
上面是docker相关配置, 希望能得到帮助

**Comment by fake2ky** [comment]
> 



> 也有可能是你启动了多个worker导致的，bot连接的worker和你api请求的worker不一致就获取不到bot了。
> 
> 一般建议只开一个worker（或者自己做跨进程共享

```
version: "2"
services:
  nonebot:
    container_name: nonebot
    build: .
    volumes:
      - "./:/app/"
      - "/usr/local/taos/driver/libtaos.so.2.4.0.5:/usr/lib/libtaos.so"
      - "/etc/taos/taos.cfg:/etc/taos/taos.cfg"
    extra_hosts:
      - "VM-12-14-centos:172.17.0.1"
    ports:
      - "9326:9326"
    env_file:
      - ".env.prod"
    environment:
      - TZ=Asia/Shanghai
      - ENVIRONMENT=prod
      - APP_MODULE=bot:app
      - SECRET=
      - ACCESS_TOKEN=
      - MAX_WORKERS=1
    network_mode: bridge
```
  问题基本解决, 目前我在docker-compose加上MAX_WORKERS=1,  尝试发送了50次没出现获取不到的情况.
  等我运行几天看看 希望不要再出现这种情况了.
  还有就是如果nonebot能提供跨进程解决方案就更好了.
